title = "roblox-modules"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© dig1t. Built with Moonwave and Docusaurus"
