[package]
name = "dig1t/profiledb"
version = "1.0.9"
description = "Module part of the dig1t/roblox-modules repository. Find the API here: https://dig1t.github.io/roblox-modules/api/ProfileDB"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.luau"]

[dependencies]
Maid = "dig1t/maid@1.1.3"
Signal = "dig1t/signal@1.0.3"
Util = "dig1t/util@1.0.19"
