[package]
name = "dig1t/badge"
version = "1.0.3"
description = "Module part of the dig1t/roblox-modules repository"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.luau"]

[dependencies]
Cache = "dig1t/cache@1.0.6"
